[package]
name = "lz_quic"
version = "0.1.0"
authors = ["Luke Horsley <luke.horsley@offset1337.co.uk>"]

[dependencies]
error-chain = "0.10.0"
tokio-core = "0.1.4"
tokio-proto = "0.1.0"
bitflags = "0.7.0"
byteorder = "1.0.0"
rand = "0.3.15"
chrono = "0.2.25"
futures = "0.1.9"
conv = "0.3.3"
hex = "0.2.0"
matches = "0.1.4"
num = "0.1.36"